DM/Web/DM.Web.Classic/Controllers/CommentariesControllers/CommentariesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using DM.Services.Authentication.Implementation.UserIdentity;
using DM.Services.Core.Dto;
using DM.Services.Forum.BusinessProcesses.Commentaries.Deleting;
using DM.Services.Forum.BusinessProcesses.Commentaries.Reading;
using DM.Services.Forum.BusinessProcesses.Likes;
using DM.Web.Classic.Extensions.RequestExtensions;
using DM.Web.Classic.Views.Shared.Commentaries;
using Microsoft.AspNetCore.Mvc;

namespace DM.Web.Classic.Controllers.CommentariesControllers
{
    public class CommentariesController : Controller
    {
        private readonly ICommentaryDeletingService commentaryDeletingService;
        private readonly ICommentaryReadingService commentaryReadingService;
        private readonly ILikeService likeService;
        private readonly IIdentityProvider identityProvider;
        private readonly ICommentariesViewModelBuilder commentariesViewModelBuilder;

        public CommentariesController(
            ICommentaryDeletingService commentaryDeletingService,
            ICommentaryReadingService commentaryReadingService,
            ILikeService likeService,
            IIdentityProvider identityProvider,
            ICommentariesViewModelBuilder commentariesViewModelBuilder)
        {
            this.commentaryDeletingService = commentaryDeletingService;
            this.commentaryReadingService = commentaryReadingService;
            this.likeService = likeService;
            this.identityProvider = identityProvider;
            this.commentariesViewModelBuilder = commentariesViewModelBuilder;
        }
        
        public async Task<IActionResult> Index(Guid entityId, int entityNumber)
        {
            if (Request.IsAjaxRequest())
            {
                var commentaries = await commentariesViewModelBuilder.BuildList(entityId, entityNumber);
                return PartialView("Commentaries/CommentariesList", commentaries);
            }
            var commentariesViewModel = await commentariesViewModelBuilder.Build(entityId, entityNumber, false);
            return PartialView("Commentaries/Commentaries", commentariesViewModel);
        }

        [HttpPost]
        public async Task<int> Remove(Guid commentaryId, Guid entityId)
        {
            await commentaryDeletingService.Delete(commentaryId);
            var (_, paging) = await commentaryReadingService.Get(entityId, PagingQuery.Empty);
            return paging.TotalPagesCount;
        }

        [HttpPost]
        public async Task<IActionResult> ToggleLike(Guid commentaryId)
        {
            var comment = await commentaryReadingService.Get(commentaryId);
            var userLiked = comment.Likes.Any(l => l.UserId == identityProvider.Current.User.UserId);
            if (userLiked)
            {
                await likeService.DislikeComment(commentaryId);
            }
            else
            {
                await likeService.LikeComment(commentaryId);
            }
            return Json(new
            {
                likesCount = comment.Likes.Count() + (userLiked ? -1 : 1),
                created = !userLiked
            });
        }
    }
}

DM/Web/DM.Web.Classic/Controllers/CommentariesControllers/CreateCommentaryController.cs
using System.Threading.Tasks;
using DM.Services.Common.Dto;
using DM.Services.Core.Dto;
using DM.Services.Forum.BusinessProcesses.Commentaries.Creating;
using DM.Services.Forum.BusinessProcesses.Commentaries.Reading;
using DM.Web.Classic.Middleware;
using DM.Web.Classic.Views.Shared.Commentaries;
using Microsoft.AspNetCore.Mvc;

namespace DM.Web.Classic.Controllers.CommentariesControllers
{
    public class CreateCommentaryController : Controller
    {
        private readonly ICommentaryCreatingService commentaryCreatingService;
        private readonly ICommentaryReadingService commentaryReadingService;

        public CreateCommentaryController(
            ICommentaryCreatingService commentaryCreatingService,
            ICommentaryReadingService commentaryReadingService)
        {
            this.commentaryCreatingService = commentaryCreatingService;
            this.commentaryReadingService = commentaryReadingService;
        }

        [HttpPost, ValidationRequired]
        public async Task<int> Create(CreateCommentaryForm createCommentaryForm)
        {
            var createComment = new CreateComment
            {
                EntityId = createCommentaryForm.EntityId,
                Text = createCommentaryForm.Text
            };
            await commentaryCreatingService.Create(createComment);
            await commentaryReadingService.MarkAsRead(createComment.EntityId);
            var (_, paging) = await commentaryReadingService.Get(createCommentaryForm.EntityId, PagingQuery.Empty);
            return paging.TotalPagesCount;
        }
    }
}

DM/Web/DM.Web.Classic/Controllers/CommentariesControllers/EditCommentaryController.cs
using System;
using System.Threading.Tasks;
using DM.Services.Common.Authorization;
using DM.Services.Common.Dto;
using DM.Services.Forum.Authorization;
using DM.Services.Forum.BusinessProcesses.Commentaries.Reading;
using DM.Services.Forum.BusinessProcesses.Commentaries.Updating;
using DM.Web.Classic.Middleware;
using DM.Web.Classic.Views.Shared.Commentaries;
using Microsoft.AspNetCore.Mvc;

namespace DM.Web.Classic.Controllers.CommentariesControllers
{
    public class EditCommentaryController : Controller
    {
        private readonly ICommentaryReadingService commentaryReadingService;
        private readonly IEditCommentaryFormBuilder editCommentaryFormBuilder;
        private readonly ICommentaryUpdatingService commentaryUpdatingService;
        private readonly IIntentionManager intentionsManager;
        private readonly ICommentaryViewModelBuilder commentaryViewModelBuilder;

        public EditCommentaryController(
            ICommentaryReadingService commentaryReadingService,
            IEditCommentaryFormBuilder editCommentaryFormBuilder,
            ICommentaryUpdatingService commentaryUpdatingService,
            IIntentionManager intentionsManager,
            ICommentaryViewModelBuilder commentaryViewModelBuilder
            )
        {
            this.commentaryReadingService = commentaryReadingService;
            this.editCommentaryFormBuilder = editCommentaryFormBuilder;
            this.commentaryUpdatingService = commentaryUpdatingService;
            this.intentionsManager = intentionsManager;
            this.commentaryViewModelBuilder = commentaryViewModelBuilder;
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid commentaryId)
        {
            var comment = await commentaryReadingService.Get(commentaryId);
            intentionsManager.ThrowIfForbidden(CommentIntention.Edit, comment);
            var editCommentaryForm = editCommentaryFormBuilder.Build(comment);
            return PartialView("Commentaries/EditCommentary", editCommentaryForm);
        }

        [HttpPost, ValidationRequired]
        public async Task<IActionResult> Edit(EditCommentaryForm editCommentaryForm)
        {
            var updateComment = new UpdateComment
            {
                CommentId = editCommentaryForm.CommentaryId,
                Text = editCommentaryForm.Text
            };
            var comment = await commentaryUpdatingService.Update(updateComment);
            var commentaryViewModel = await commentaryViewModelBuilder.Build(comment);
            return PartialView("Commentaries/Commentary", commentaryViewModel);
        }
    }
}

DM/Web/DM.Web.Classic/Views/Shared/Commentaries/Commentaries.cshtml
@model DM.Web.Classic.Views.Shared.Commentaries.CommentariesViewModel

<h3 class="content-mediumTitle">Комментарии</h3>
<div id="Paginator" class="paginator"></div>
<div id="Container">
    @await Html.PartialAsync("Commentaries/CommentariesList", Model.Commentaries)
</div>
<div class="paginator-fixed-wrapper">
    <div id="PaginatorHover" class="paginator-fixed"></div>
</div>
@if (Model.CanCreate)
{
    @await Html.PartialAsync("Commentaries/CreateCommentary", Model.CreateCommentaryForm)
}
else
{
    <div class="content-noAccessMessage">@ViewData["NoAccessMessage"]</div>
}

DM/Web/DM.Web.Classic/Views/Shared/Commentaries/CommentariesList.cshtml
@model DM.Web.Classic.Views.Shared.Commentaries.CommentaryViewModel[]
@if (Model.Length > 0)
{
    foreach (var comment in Model)
    {
        @await Html.PartialAsync("Commentaries/Commentary", comment)
    }
}
else
{
    <div id="NoCommentariesMessage">Здесь еще никто ничего не написал</div>
}

DM/Web/DM.Web.Classic/Views/Shared/Commentaries/Commentary.cshtml
@using DM.Web.Classic.Extensions.IconFontExtensions
@using DM.Web.Classic.Extensions.UserExtensions
@using DM.Web.Classic.ViewComponents.Shared.HumanDate
@using Microsoft.AspNetCore.Routing
@model DM.Web.Classic.Views.Shared.Commentaries.CommentaryViewModel
<div class="comment js-entity-wrapper" id="Entity_@(Model.CommentaryId)" data-entity-id="@Model.CommentaryId">
    <div class="comment-wrapper" id="EntityContent_@(Model.CommentaryId)">
        <div class="comment-actions">
            @if (Model.CanEdit)
            {
                <a href="@Url.Action("Edit", "EditCommentary", new RouteValueDictionary {{"commentaryId", Model.CommentaryId}})" id="EditEntityLink_@(Model.CommentaryId)">@IconFont.Render(IconType.Edit)</a>
            }
            @if (Model.CanRemove)
            {
                <a href="@Url.Action("Remove", "Commentaries",
                             new RouteValueDictionary
                             {
                                 {"commentaryId", Model.CommentaryId},
                                 {"entityId", Model.EntityId}
                             })" id="RemoveEntityLink_@(Model.CommentaryId)">@IconFont.Render(IconType.Remove)</a>
            }
        </div>
        <div class="comment-content">@Html.Raw(Model.Text)</div>
        <div class="comment-data">
            @Html.UserLink(Model.Author, withBadge: true),
            @await Component.InvokeAsync(nameof(HumanizedDate), new {date = Model.CreateDate})
            @if (Model.LastUpdateDate.HasValue)
            {
                @:(последний раз редактировался @await Component.InvokeAsync(nameof(HumanizedDate), new {date = Model.LastUpdateDate.Value}))
            }
            <span class="comment-likes-wrapper@(Model.LikesCount > 0 ? " comment-likes-wrapper-hasLikes" : string.Empty)">
                @if (Model.CanLike)
                {
                    <a href="@Url.Action("ToggleLike", "Commentaries", new RouteValueDictionary {{"commentaryId", Model.CommentaryId}})" class="comment-likes @(Model.HasLiked ? "comment-likes-active" : string.Empty)" id="ToggleEntityLikeLink_@(Model.CommentaryId)">
                        @IconFont.Render(IconType.Like, new Dictionary<string, object> { { "class", "comment-likes-icon" } })
                        <span id="EntityLikesCounter_@(Model.CommentaryId)">
                            @if (Model.LikesCount > 0)
                            {
                                @Model.LikesCount
                            }
                        </span>
                    </a>
                }
                else if (Model.LikesCount > 0)
                {
                    <span class="comment-likes">
                        @IconFont.Render(IconType.Like, new Dictionary<string, object> { { "class", "comment-likes-icon" } }) @Model.LikesCount
                    </span>
                }
            </span>
        </div>
    </div>
    <div class="comment-edit-form-wrapper"></div>
</div>

DM/Web/DM.Web.Classic/Views/Shared/Commentaries/CreateCommentary.cshtml
@using DM.Web.Classic.Extensions.HtmlHelperExtensions
@model DM.Web.Classic.Views.Shared.Commentaries.CreateCommentaryForm
<h3 class="content-minorTitle">Ваш комментарий</h3>
@using (Html.BeginForm("Create", "CreateCommentary", FormMethod.Post, new Dictionary<string, object> {{"id", "CreateForm"}}))
{
    @Html.HiddenFor(m => m.EntityId)
    <div class="createCommentary-wrapper">
        @await Html.SmartTextAreaFor(m => m.Text, Model.Parser, new Dictionary<string, object>
        {
            {"class", "commentary-textarea"},
            {"placeholder", "Введите текст комментария и нажмите Ctrl+Enter, чтобы отправить"}
        })
    </div>
    @Html.Submit("Добавить комментарий", new Dictionary<string, object> {{"class", "form-submit-button"}})
}

DM/Web/DM.Web.Classic/Views/Shared/Commentaries/EditCommentary.cshtml
@using DM.Web.Classic.Extensions.HtmlHelperExtensions
@model DM.Web.Classic.Views.Shared.Commentaries.EditCommentaryForm
@using (Html.BeginForm("Edit", "EditCommentary", FormMethod.Post, new {id = $"EditForm_{Model.CommentaryId}"}))
{
    @Html.HiddenFor(m => m.CommentaryId)
    <div class="editCommentary-wrapper">
        @await Html.SmartTextAreaFor(m => m.Text, Model.Parser, new Dictionary<string, object>
        {
            {"class", "commentary-textarea"},
            {"placeholder", "Введите текст комментария и нажмите Ctrl+Enter, чтобы отправить или Esc, чтобы отменить"}
        })
    </div>
    @Html.Submit("Сохранить изменения", new Dictionary<string, object> {{"class", "smallButton form-submit-button"}})
    <a href="javascript:void(0)" id="CancelEditLink_@(Model.CommentaryId)">Отменить</a>
}