DM/Web/DM.Web.Classic/Controllers/SearchController.cs
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using DM.Services.Core.Exceptions;
using DM.Web.Classic.Extensions.RequestExtensions;
using DM.Web.Classic.Views.Search;
using Microsoft.AspNetCore.Mvc;

namespace DM.Web.Classic.Controllers
{
    public class SearchController : Controller
    {
        private readonly ISearchViewModelBuilder searchViewModelBuilder;

        public SearchController(
            ISearchViewModelBuilder searchViewModelBuilder)
        {
            this.searchViewModelBuilder = searchViewModelBuilder;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string query, SearchLocation location, int entityNumber)
        {
            var searchViewModel = await searchViewModelBuilder.Build(query, location, entityNumber);
            return Request.IsAjaxRequest()
                ? (IActionResult) PartialView("SearchEntries", searchViewModel)
                : View(searchViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> UserAutocomplete(string query)
        {
            var result = await searchViewModelBuilder.BuildAutocomplete(query);
            return result.Any()
                ? Ok(result)
                : throw new HttpException(HttpStatusCode.NotFound, "Nothing found");
        }
    }
}

DM/Web/DM.Web.Classic/Views/Search/Index.cshtml
@using DM.Web.Classic.Extensions.HtmlHelperExtensions
@using DM.Web.Classic.Extensions.HtmlHelperExtensions.Dropdown
@model DM.Web.Classic.Views.Search.SearchViewModel
@{
    ViewBag.Title = "Поиск по сайту";
    Layout = "~/Views/Shared/Layout/_TwoColumnLayout.cshtml";
}

@section LeftColumn
{
    @await Html.PartialAsync("Layout/LeftBar/GeneralLeftColumn")
}

<h1 class="content-pageTitle">@ViewBag.Title</h1>

@using (Html.BeginForm("Index", "Search", FormMethod.Get))
{
    @Html.TextBox("query", Model.Query, new {placeholder = "Что ищем"})
    @:и где:
    @Html.DropdownFor(x => x.Location, inputHtmlAttributes: new Dictionary<string, object>
    {
        ["name"] = Model.Location
    })
    @Html.Submit("Найти")
}

@if (Model.Results != null)
{
    if (Model.Results.Any())
    {
        @await Html.PartialAsync("SearchEntries", Model)
    }
    else
    {
        @:Увы, по вашему запросу ничего не найдено
    }
}

@section FooterScript {
    <script>
        DM.Ready();
    </script>
}

DM/Web/DM.Web.Classic/Views/Search/SearchEntries.cshtml
@model DM.Web.Classic.Views.Search.SearchViewModel
@foreach (var entry in Model.Results)
{
    @await Html.PartialAsync("SearchEntry", entry)
}

DM/Web/DM.Web.Classic/Views/Search/SearchEntry.cshtml
@model DM.Web.Classic.Views.Search.SearchEntryViewModel
<div>@Html.Raw(Model.Title)</div>
<div>@Html.Raw(Model.Text)</div>
<hr />